### ISSUE TITLE
Publishing pinject v0.12 with Python 3 support

### ISSUE THREAD

**Issue by huan** [google/pinject#26]
Hi there(_who are looking for the Python3 support of pinject for a long time_)!

We had just merged #19 (thanks @trein for the great work!) and staging a test version v0.11 on test.pypi.org.

Please install the dev version of pinject by running the following pip command:

```sh
pip install \
  --no-deps \
  --no-cache \
  --upgrade \
  --index-url https://test.pypi.org/simple/ \
  pinject
```

Then let us know whether it works under your environment.

We will publish the v0.12 version to pypi.org as an official release after we confirmed the v0.11 is work as expected by collecting enough confirmation replies under this issue.

Thanks for your help and let's looking forward to the v0.12 release!

**Comment by huan** [comment]
Hi @rncry, I noticed that you had created the PR #28 but you closed that after a while.

Please let me know what I need to do to follow your contribution.

And also if there's something not right in the correct code base, could you please add a unit test so that the automation tests could fail and point that problem out?

Thank you very much.

**Comment by rncry** [comment]
Hey, sorry I don't think I'll be able to officially contribute without a lot of legal wrangling (it's possible but would take a while to sort out, and I didn't think it'd be worth it for such a minor change!)

The only issue is that setup.py includes a reference to third_party which has been deleted in #19 so trying to install the code is likely to fail using:

$ python setup.py install / bdist / develop / etc

I'm not sure how your tooling is set up but it may catch this already.

**Comment by rncry** [comment]
I'd have to get legal approval from my work to sign it (long story! ;))

You might have a slightly different checkout? Here's the error from a fresh checkout of master:

`python setup.py sdist bdist_wheel
running sdist
running egg_info
writing pinject.egg-info/PKG-INFO
writing dependency_links to pinject.egg-info/dependency_links.txt
writing requirements to pinject.egg-info/requires.txt
writing top-level names to pinject.egg-info/top_level.txt
error: package directory 'pinject/third_party' does not exist`

**Comment by huan** [comment]
Yes, you are right: after I do a fresh checkout, I got this error.

Appreciate for pointing this out, I had just added a commit in my PR to fix that, and the test.pypi.org had been updated to v0.11.3.

Please let me know if there are any other problems, thank you very much!

**Comment by rncry** [comment]
no problem :) I'm excited to get this on py3

**Comment by huan** [comment]
Pinject v0.12 Released.

See: https://github.com/google/pinject/releases/tag/v0.12
