### ISSUE TITLE
Getting FileNotFoundError: [Errno 2] No such file or directory: '<my-path>/site-packages/pinject/../VERSION'

### ISSUE THREAD

**Issue by rmiller-sgntr** [google/pinject#31]
I am getting this error when installing the latest version (0.12.2) with `pip install pinject`:

> File "/home/ronen/reach/reach_venv3.6/lib/python3.6/site-packages/pinject/version.py", line 10, in <module>
    VERSION = open(VERSION_FILE).read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/home/ronen/reach/reach_venv3.6/lib/python3.6/site-packages/pinject/../VERSION'

So I have looked and there isn't really any `VERSION` file in my `site-packages` folder (should there be?).
I am running `python3.6.7` on `Ubuntu 18.04`. We have been running with django and pinject for a long time now and everything was great.

Please help, thanks in advance!

**Comment by logavanc** [comment]
No, that VERSION file is being looked for outside of the module directory and should not be there when the package is installed from the repos.
It looks like the `version.py` file should be generated at the same time as the `VERSION` file by the `Makefile`?

**Comment by logavanc** [comment]
Something like https://github.com/google/pinject/pull/34 could fix the issue, but I am not sure about the version bump... maybe I should have forked from `v0.12.2` or something.

**Comment by rmiller-sgntr** [comment]
YES! Looking good. Have you tried installing it?

**Comment by logavanc** [comment]
Yeah, I just have the `pinject/version.py` file modified locally until @huan gets a chance to look at my pull request. Working great. Not sure what it will take to get the change released all the way out to https://pypi.org though.

**Comment by huan** [comment]
Thank you @rmiller-sgntr for reporting this issue, and thank you @logavanc for the Pull Request to fix this!

It's my fault that I should not read a non-exist file outside the module directory.

**Comment by huan** [comment]
`pinject@0.12.6`has just published on pypi.org, please test and let me know if it works, thank you very much!

**Comment by logavanc** [comment]
Working great for me this morning! Thank you! Keep up the good work on this project!

**Comment by huan** [comment]
Glad to hear that, cheers!

**Comment by rmiller-sgntr** [comment]
For me as well. Thanks you guys for the quick fix and release!
