### ISSUE TITLE
ObjectGraph Builder

### ISSUE THREAD

**Issue by 0mars** [google/pinject#42]
Hi, I've developed a builder for having a multiple step configurations, or a configuration manager that can be imported from different places, configured and in the end can build the object graph.

I've made a different repo, since I wanted to use it immediately for my own project, however I'm opening this ticket as a suggested, if you are interested in integrating it with the original package, I'd be happy to port it, open a PR and shut down the additional package.

This is the package, and please check the documentation for use cases.
https://github.com/eshta/object-graph-builder

Please let me know your thoughts, and thanks :)

**Comment by loweryjk** [comment]
Not an issue. Can we close this please?
