### ISSUE TITLE
latest release on pypi is 0.14.1 but on github it's 0.15.3

### ISSUE THREAD

**Issue by MrGreenTea** [google/pinject#52]
Is there a reason for skipping `Deploy` [here](https://github.com/google/pinject/actions/runs/75562440)?

The last release on pypi is 0.14.1, which is missing some fixes like #46 

Publishing the latest version to pypi.org would be very much appreciated!

Thanks for the great tool.

**Comment by huan** [comment]
Oh, the reason that it was skipped is that the version number has not been bumped in the latest update.

If a version has already published then we can not publish it twice in PyPI.

please feel free to send a PR to bump the VERSION file in the root of our repo, and I'd like to merge it and help you to get a new version published.

**Comment by MrGreenTea** [comment]
Thanks for clearing that up, my mistake :)
