### ISSUE TITLE
Unable to import pinject

### ISSUE THREAD

**Issue by dmitrybelyakov** [google/pinject#7]
Hello,
I decided to give pinject a try, but unfortunately it does not import. Here's what I do: install pinject with `pip install pinject` and then interactively `import pinject`.

It seem to fail on line 156 of `third_party/decorator.py`. I'm on python 3.4 so maybe that's the reason although looking at code I can see blocks dealing with python >3.2 

Is that a bug?

**Comment by AlexKovalevych** [comment]
Still getting this issue:

```
SyntaxError: Missing parentheses in call to 'exec'
```

at pinject/third_party/decorator.py", line 156

**Comment by trein** [comment]
@AlexKovalevych, what is your Python version? Are you using the patched revision?

**Comment by AlexKovalevych** [comment]
@trein  its 3.4.2. no, i don't think so, i've installed the master branch

**Comment by trein** [comment]
@AlexKovalevych so the master branch does not have support for Python 3. I submitted a fix for this, but it hasn't been merged yet. If you want, you can cherry-pick it: https://github.com/trein/pinject/commit/fd091eb2237547f921f7ada531e16b95ba6693b8

**Comment by AlexKovalevych** [comment]
@trein understood, weird its not being merged yet, thank you for response

**Comment by zixia** [comment]
+1 Is there anyone here?

Please merge the PRs to fix the issues, esp: Python 3 Support.

Thanks!

**Comment by dmitrybelyakov** [comment]
@zixia heya! i don't think there is, but apparently it is quite easy to implement a di solution yourself - took me about 2 hours to write my own injector/container with tests and all

**Comment by zixia** [comment]
Thanks! I'll go to take a look. It seems you did a great job!

However, I'm a newbie of Python, I'm familiar with DI & Angular but I'd like to use an out-of-box DI solution in python.

I love this pinject because it's decorator free! :+1:
